version: '3.8'
services:
  app:
    build: .
#    command: node dist/main.js
    command: npm start
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    working_dir: /usr/src/app
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DATABASE_URL: db://postgres:postgres@db:5432/nest_app
      DB_HOST: db
      DB_PORT: 5432
      REDIS_URL: redis://redis:6379
      PORT: 3000

  redis:
    image: "redis/redis-stack:latest"
    ports:
      - "6379:6379"

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOSTS: redis
    ports:
      - "8081:8081"
    depends_on:
      - redis

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_app
    ports:
      - "5412:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
