version: '3.8'
services:
#  app:
#    build: .
#    command: node dist/main.js
#    volumes:
#      - .:/usr/src/app
#      - /usr/src/app/node_modules
#    working_dir: /usr/src/app
#    ports:
#      - "3000:3000"
#    depends_on:
#      - db

  db:
    image: postgres:13
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: nest_app
    ports:
      - "5412:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres_data:
